// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTuQAW45oH6n1_tX0pNnnmehmT3kmZH4',
    appId: '1:250046250659:web:411638f2cf3deb339c8916',
    messagingSenderId: '250046250659',
    projectId: 'esp8266-teste-d9365',
    authDomain: 'esp8266-teste-d9365.firebaseapp.com',
    databaseURL: 'https://esp8266-teste-d9365-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-teste-d9365.appspot.com',
    measurementId: 'G-9KFZDVE672',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELq6udRZ2U98UmcCmO0wcRncCMtQPDqM',
    appId: '1:250046250659:android:de303dfe8c0d0c2b9c8916',
    messagingSenderId: '250046250659',
    projectId: 'esp8266-teste-d9365',
    databaseURL: 'https://esp8266-teste-d9365-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-teste-d9365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLdA9diivk2F0co3FoaZ6kh8_EkDUhzvE',
    appId: '1:250046250659:ios:af637d2fe59a07b49c8916',
    messagingSenderId: '250046250659',
    projectId: 'esp8266-teste-d9365',
    databaseURL: 'https://esp8266-teste-d9365-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-teste-d9365.appspot.com',
    iosClientId: '250046250659-3c7sh8h25iqfjtkede8cffrp5dk5ovb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCaixaAgua',
  );
}
